export const ROUTER = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  VERIFY_EMAIL: "/verify-email",
  PROFILE: "/profile",
  USERS: "/users",
  USER: "/users/[id]",
  USER_EDIT: "/users/[id]/edit",
  USER_CREATE: "/users/create",
  POKEMON: "/pokemon",
  POKEMON_DETAIL: "/pokemon/[id]",
  POKEMON_CREATE: "/pokemon/create",
  POKEMON_EDIT: "/pokemon/[id]/edit",
  POKEMON_TYPE: "/pokemon-type",
  POKEMON_TYPE_DETAIL: "/pokemon-type/[id]",
  POKEMON_TYPE_CREATE: "/pokemon-type/create",
  POKEMON_TYPE_EDIT: "/pokemon-type/[id]/edit",
};
